Update TokenBridgeLib.sol
bane-labs/bridge-evm-contracts pull request #109
Opened 2024-05-29 06:51 UTC by passer-byzhang

Use safeTransfer to prevent from directly throwing an error when the transfer transaction fails.
For example, [default ERC20 token contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L104) will revert error instead of return a `false` if the transfer failed.

2024-05-29 12:02 UTC, mialbu commented on contracts/library/TokenBridgeLib.sol
> +        return success && (returndata.length == 0 || abi.decode(returndata, (bool))) && address(_neoXToken).code.length > 0;
Hmm, `address(_neoXToken).code.length > 0` looks interesting here. Is there a specific reasoning for having this check here at the end of the function?

If not, I think it might make more sense if we do such a check outside of this function, i.e., before calling this function in the first place. That way we're also doing the check only once if this function here is called multiple times (assuming `selfdestruct` is not executed in the `_neoXToken` contract during a `transfer` invocation...😅🫣). For example doing this check before the following loop in the `depositToken` function:

https://github.com/bane-labs/bridge-evm-contracts/blob/0c2d7e705a3b8171575942145133a3dfd60d68e7/contracts/bridge/BridgeImpl.sol#L363-L387

and before the execution in a claim:
https://github.com/bane-labs/bridge-evm-contracts/blob/0c2d7e705a3b8171575942145133a3dfd60d68e7/contracts/bridge/BridgeImpl.sol#L421

If you still want to have it directly here in this function, I propose we do it before executing the call and just return `false` if it applies:

```suggestion
        if (address(_neoXToken).code.length == 0) {
                return false;
        }
        bytes memory transferCall = abi.encodeCall(IERC20.transfer, (_to, _amount));
        (bool success, bytes memory returndata) = address(_neoXToken).call(transferCall);
        return success && (returndata.length == 0 || abi.decode(returndata, (bool)));
```

2024-05-29 13:06 UTC, passer-byzhang commented on contracts/library/TokenBridgeLib.sol
> +        return success && (returndata.length == 0 || abi.decode(returndata, (bool))) && address(_neoXToken).code.length > 0;
You are right, It is better to check outside of this function.
I just rememered that every single `neoXToken` can only be registered by `governor`and every token address is controllable. So I'm not sure it's necessary😵‍💫. If it's neccesary , I will add this check in front of the loop as you say.

2024-05-29 16:22 UTC, mialbu commented on contracts/library/TokenBridgeLib.sol
> +        return success && (returndata.length == 0 || abi.decode(returndata, (bool))) && address(_neoXToken).code.length > 0;
Afaik, if `_neoXToken` has no deployed code, `success` will be `false` and the `returndata` will be empty after executing the `.call()`. Can you verify that statement?

If so, we **can** add the check as you said outside of this function before it's called. However, I'm not so sure we really need it.

Let's talk about some scenario:
If a registered token address uses `selfdestruct`\*, the worst that can happen, afaik, is that that the relayer keeps invoking `depositToken` for that token address (assuming deposits keep coming in on N3). Ultimately adding all the new deposits to this token bridge's claimable mapping and _paying for the transactions_. However, if there's still deposits coming in on N3, the transactions have been paid for anyway. So I don't really see a considerable risk here. This specific token bridge will go _out of service_ in any way if something like this would happen (and it'll only happen if the token admin decides to destroy the token anyway😅).

So: The scenario seems very unlikely to happen for me AND if it would it won't be a security issue. Hence, I think we don't need the check.

\* We should check if the `_neoXToken` address has code in the registration. I'm actually not sure if we do.

2024-05-30 04:14 UTC, passer-byzhang commented on contracts/library/TokenBridgeLib.sol
> +        return success && (returndata.length == 0 || abi.decode(returndata, (bool))) && address(_neoXToken).code.length > 0;
Thank you for your analysis!  It makes sense. I will remove this check. Despite that  `success` will be `true` and `returndata` will be empty if the target addresss has no code , this case would never happen because each token should be checked off-chain before `groverner` register it.(such as verifying in explorer or audit report, we can avoid that contract contains a `selfdestruct` in that step).

2024-05-30 06:19 UTC, txhsl approved these changes

2024-05-30 07:03 UTC, mialbu approved these changes

2024-05-30 07:32 UTC, mialbu requested changes

2024-05-30 07:32 UTC, mialbu commented on contracts/bridge/BridgeImpl.sol
> +        if(!success) revert TransferFailed();
Oh, good catch, that was a bug.

Minor format though:
```suggestion
        bool success = TokenBridgeLib._executeERC20Transfer(_neoXToken, claimable.amount, to);
        if (!success) revert TransferFailed();
```

2024-05-30 08:00 UTC, mialbu approved these changes

2024-05-30 08:01 UTC, merged