Add unitest
bane-labs/bridge-evm-contracts pull request #115
Opened 2024-06-06 07:55 UTC by passer-byzhang

unitest for `depositeToken`,`claimToken` and `withdrawToken`

2024-06-12 16:02 UTC, mialbu requested changes
Great tests! 👏🙏

Most comments are about the format. Please have a look at them. If you're adding more test cases I'd appreciate it if you could do that in a different PR, so that it's easier for the reviewer. Took me quite to have a look at everything here. 😅

I very much liked the comments in the BridgeTest. It makes it a lot easier to read the test code if you can read in natural language what the test should do. Could you add some description to the TokenBridge tests as well? Especially with the more complex scenarios there. This would be much appreciated and will increase maintainability by a lot if we need to adapt tests for contract upgrades. Also, this will likely make it easier for auditors to understand the specific expected behavior more precisely.

So, in summary, please generally...
- ...use camel case for variables, e.g., instead of `getTokenbridge` use `getTokenBridge`.
- ...remove unnecessary blocks with multiple empty lines
- ...make sure every file has an empty line at the end of the file
- ...remove the `console.log`s (mainly in the token bridge test file)
- ...add some description to the token bridge tests (some inline comments and on top what the test wants to accomplish, e.g., `If the contract has insufficient funds, the deposit amounts should be made available for claiming.`

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/MockERC20.sol
> +}
empty line

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/SigUtils.sol
> +
format, 1 empty line is sufficient.

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/SigUtils.sol
> +import "../library/BridgeLib.sol";
format, empty lines between pragma/import/contract.

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/SigUtils.sol
> +                    _depositData.nonce
This order looks wrong. The concatenation is in the order `nonce`, `to`, `amount`. The concatenation here looks like the reverse of the previous concatenation order. Is there a reason it was reversed?

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/TestBridge.sol
> +import "../bridge/BridgeImpl.sol";
format

2024-06-12 16:02 UTC, mialbu commented on .states/vm-cancun/state.json
> +}
Please add an empty lines in every file.

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/SigUtils.sol
> +}
empty line

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/TestBridge.sol
> +
format. ok I stop commenting this. Please just make sure to remove blocks of multiple unnecessary empty lines, and make sure each file has an empty line at the end of the file.

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +    address public user = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
The `user` has the role of the funder, please rename it to `funder` and use different address than relayer.

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +        // console.log("msg.sender: %s, token: %s",msg.sender,neoXToken);
remove

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/TestBridge.sol
Does Foundry not support reading public variables, or why do we need these wrapped functions?

For the boolean `isRegisteredToken` I get the point of having it, since it has additional logic to just reading. However, I don't see the point for the other getters, e.g., `getNeoN3Token`.

2024-06-12 16:02 UTC, mialbu commented on contracts/tests/TestBridge.sol
> +    ) public returns (bytes32) {
```suggestion
    ) public pure returns (bytes32) {
```

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +        bridgeImpl.registerToken(neoXToken, validConfig); // Should fail
```suggestion
        bridgeImpl.registerToken(neoXToken, validConfig);
```

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +    function test_RegisterTokenByNonGovernorr() public {
```suggestion
    function test_RegisterTokenByNonGovernor() public {
```

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +        // emit bridgeImpl.TokenUnregister(neoXToken,validConfig);
Can you add an actual check if the event is emitted as expected?

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +        // // Verify that the token bridge is unregistered
```suggestion
        // Verify that the token bridge is unregistered
```

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +            abi.encodeWithSignature("TokenBridgeUnpaused(address)", neoXToken)
👍🏼 good test. Got me thinking, maybe we should use a formal check here if a token is registered instead of reverting with `TokenBridgeUnpaused`. Reverting with `TokenBridgeNotRegistered` is better suited here.

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +        // vm.expectRevert(abi.encodeWithSelector(BridgeStorage.TokenBridgeNotRegistered.selector,unregisteredToken));
```suggestion
```

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +    // constructor(address _management) BridgeImpl(_management) {}
Please move this to where the `TestBridge` is instantiated, i.e., line 55.

2024-06-12 16:02 UTC, mialbu commented on test/BridgeManagement.t.sol
> +    address public user = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
rename to `funder` and use different address than relayer.

2024-06-12 16:02 UTC, mialbu commented on test/Bridge.t.sol
> +    uint256[] public validatorsKeys;
Not needed in this test, please remove it.

2024-06-12 16:02 UTC, mialbu commented on test/BridgeManagement.t.sol
> +            assertEq(x, validatorsAddresses[i]);
```suggestion
            address recoveredAddr = ecrecover(ethHash, v, r, s);
            _signatures[i] = BridgeLib.Signature(v, r, s);
            assertEq(recoveredAddr, validatorsAddresses[i]);
```

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +    // constructor(address _management) BridgeImpl(_management) {}
move to instantiation.

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +    address public user = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
rename to `funder` and use different address than relayer. Also, please use different addresses for transfer recipients, i.e., addresses that don't have any role in the bridge management.

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +    ) public view returns (BridgeLib.Signature[] memory) {
This always takes the signatures of the first 5 validators. I think we should at least have 1 or 2 tests where validators 6 and 7 are also involved. Maybe you could add an int array of size 5 as parameter (for indexes), so that you can specify which validators should sign the root.

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +        );
Can you add a check that tests the `TokenClaimable` event here?

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +            amount: 100,
Maybe use different value than `100` here - differentiating a bit more with the `100 ether` mint in the beginning of the test. I overlooked the `ether` and expected a different test case. Or leave it like it is and just add a comment at the beginning of the test stating the obvious. 🙂

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +        );
```suggestion
```

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +        //check withdrwal state and missing max/min deposit amount check in depositToken?
Yes, such tests would be great.

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +    // todo deposittoken到底需不需要relayer
I don't understand the todo 🥲 please commit in english 😅

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +        // vm.expectRevert("not relayer");
The newest version requires the relayer, so it should revert here now.

```suggestion
        vm.expectRevert("not relayer");
```

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +        bridgeImpl.registerToken(neoXTokenA, validConfigA);
```suggestion
        // validConfigA.maxDeposits is 2
        bridgeImpl.registerToken(neoXTokenA, validConfigA);
```

2024-06-12 16:02 UTC, mialbu commented on test/FungibleToken.t.sol
> +        depositData[1] = d1;
I'm a bit confused as to why the third depositData has not been added here. If the data is not needed, I assume none of the data is needed. Can't we just use an empty array of type `BridgeLib.DepositData` with size 3 for this test and get the same revert reason?

2024-06-19 03:40 UTC, moonpyt commented on contracts/tests/MockERC20.sol
> +}
Have been modified

2024-06-19 03:40 UTC, moonpyt commented on contracts/tests/SigUtils.sol
> +
Have been modified

2024-06-19 03:41 UTC, moonpyt commented on contracts/tests/SigUtils.sol
> +import "../library/BridgeLib.sol";
Have been modified

2024-06-19 03:41 UTC, moonpyt commented on contracts/tests/SigUtils.sol
> +                    _depositData.nonce
Have been modified

2024-06-19 03:41 UTC, moonpyt commented on contracts/tests/TestBridge.sol
> +import "../bridge/BridgeImpl.sol";
Have been modified

2024-06-19 03:42 UTC, moonpyt commented on .states/vm-cancun/state.json
> +}
Have been modified

2024-06-19 03:43 UTC, moonpyt commented on contracts/tests/SigUtils.sol
> +}
Have been modified

2024-06-19 03:43 UTC, moonpyt commented on contracts/tests/TestBridge.sol
> +
Have been modified

2024-06-19 03:44 UTC, moonpyt commented on test/Bridge.t.sol
> +    address public user = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
Have been modified

2024-06-19 03:44 UTC, moonpyt commented on test/Bridge.t.sol
> +        // console.log("msg.sender: %s, token: %s",msg.sender,neoXToken);
Have been modified

2024-06-19 03:48 UTC, moonpyt commented on contracts/tests/TestBridge.sol
I added the case to use the getNeoN3Token method and changed getNeoN3Token for reading. Modified the getTokenConfig, getTokenbridgePaused methods to get the paused state of the bridge (because there is no way to get it, it can only be obtained by the variable value)

2024-06-19 03:49 UTC, moonpyt commented on contracts/tests/TestBridge.sol
> +    ) public returns (bytes32) {
Have been modified

2024-06-19 03:49 UTC, moonpyt commented on test/Bridge.t.sol
> +        bridgeImpl.registerToken(neoXToken, validConfig); // Should fail
Have been modified

2024-06-19 03:50 UTC, moonpyt commented on test/Bridge.t.sol
> +    function test_RegisterTokenByNonGovernorr() public {
Have been modified

2024-06-19 03:54 UTC, moonpyt commented on test/Bridge.t.sol
> +        // emit bridgeImpl.TokenUnregister(neoXToken,validConfig);
registerToken/unregisterToken pauseToken/unPausetoken depositToken/withdrawToken  all the successful case of these methods, have added a check event case

2024-06-19 03:54 UTC, moonpyt commented on test/Bridge.t.sol
> +        // // Verify that the token bridge is unregistered
Have been modified

2024-06-19 03:57 UTC, moonpyt commented on test/Bridge.t.sol
> +        // vm.expectRevert(abi.encodeWithSelector(BridgeStorage.TokenBridgeNotRegistered.selector,unregisteredToken));
Have been modified

2024-06-19 03:58 UTC, moonpyt commented on test/Bridge.t.sol
> +    // constructor(address _management) BridgeImpl(_management) {}
Have been modified

2024-06-19 03:58 UTC, moonpyt commented on test/BridgeManagement.t.sol
> +    address public user = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
Have been modified

2024-06-19 03:59 UTC, moonpyt commented on test/BridgeManagement.t.sol
> +            assertEq(x, validatorsAddresses[i]);
Have been modified

2024-06-19 03:59 UTC, moonpyt commented on test/FungibleToken.t.sol
> +    // constructor(address _management) BridgeImpl(_management) {}
Have been modified

2024-06-19 04:02 UTC, moonpyt commented on test/FungibleToken.t.sol
> +    ) public view returns (BridgeLib.Signature[] memory) {
Have been modified,Several test cases were added using any 6 nodes/any 5 nodes/all 7 nodes to depositToken and withdrawToken

2024-06-19 04:04 UTC, moonpyt commented on test/FungibleToken.t.sol
> +        );
Have been modified

2024-06-19 04:04 UTC, moonpyt commented on test/FungibleToken.t.sol
> +    // todo deposittoken到底需不需要relayer
Have been modified

2024-06-19 04:04 UTC, moonpyt commented on test/FungibleToken.t.sol
> +        // vm.expectRevert("not relayer");
Have been modified

2024-06-19 04:05 UTC, moonpyt commented on test/FungibleToken.t.sol
> +        bridgeImpl.registerToken(neoXTokenA, validConfigA);
Have been modified

2024-06-19 04:05 UTC, moonpyt commented on test/FungibleToken.t.sol
> +        depositData[1] = d1;
Have been modified

2024-06-19 04:06 UTC, moonpyt commented on test/Bridge.t.sol
> +            abi.encodeWithSignature("TokenBridgeUnpaused(address)", neoXToken)
Waiting for your modification

2024-06-19 04:06 UTC, moonpyt commented on test/FungibleToken.t.sol
> +        //check withdrwal state and missing max/min deposit amount check in depositToken?
Waiting for your modification

2024-06-19 04:07 UTC, moonpyt commented on test/Bridge.t.sol
> +    uint256[] public validatorsKeys;
The bridge.t.sol file needs this to initialize the management contract before it can execute other cases

2024-06-19 04:09 UTC, moonpyt commented on test/FungibleToken.t.sol
> +    address public user = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
Modified use to funder

2024-06-19 04:51 UTC, moonpyt commented on test/FungibleToken.t.sol
> +        );
Have been modified

2024-06-19 05:31 UTC, moonpyt commented on test/FungibleToken.t.sol
> +    address public user = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
"addresses that don't have any role in the bridge management"  - Have been modified

2024-06-19 05:32 UTC, moonpyt commented on test/FungibleToken.t.sol
> +            amount: 100,
Have been modified，Some cases use different transfer amounts，It's not just 100 or 100ether

2024-06-19 15:22 UTC, mialbu commented on test/Bridge.t.sol
> +    uint256[] public validatorsKeys;
My mistake, GitHub shows at least 4 lines, so the lines before the one I marked are shown as well here, but I think I only meant the `uint256[] public validatorsKeys;`.

2024-06-20 02:31 UTC, moonpyt commented on test/Bridge.t.sol
> +    uint256[] public validatorsKeys;
Ok, modified

2024-06-20 08:03 UTC, mialbu commented on test/Bridge.t.sol
> +            abi.encodeWithSignature("TokenBridgeUnpaused(address)", neoXToken)
I'm not doing that right now, you don't need to wait for this.

I've opened an issue for it (https://github.com/bane-labs/bridge-evm-contracts/issues/123).

2024-06-20 08:04 UTC, mialbu commented on test/FungibleToken.t.sol
> +        //check withdrwal state and missing max/min deposit amount check in depositToken?
Which modification do you mean, @moonpyt ?

2024-06-20 08:16 UTC, moonpyt commented on test/Bridge.t.sol
> +            abi.encodeWithSignature("TokenBridgeUnpaused(address)", neoXToken)
Well.

2024-06-20 08:32 UTC, moonpyt commented on test/FungibleToken.t.sol
> +        //check withdrwal state and missing max/min deposit amount check in depositToken?
My mistake,Checking withdrwal state is something I do，                                                                              
but I think depositToken method may need check tokenValue < config.minAmount and  tokenValue > config.maxAmount

2024-06-20 13:22 UTC, mialbu commented on test/FungibleToken.t.sol
> +        //check withdrwal state and missing max/min deposit amount check in depositToken?
That's not necessary in the deposit functions. These values are already checked on the Neo N3 side when someone deposits gas or a token. These min/max values are used when someone wants to bridge to the other chain.

The same applies for withdrawals: The min/max values are checked here in this contract on Neo X, then the check is not done again when the relayer distributes the gas/tokens on Neo N3.

2024-06-21 03:06 UTC, moonpyt commented on test/FungibleToken.t.sol
> +        //check withdrwal state and missing max/min deposit amount check in depositToken?
Ok, got it

2024-07-04 18:48 UTC, mialbu approved these changes
LGTM

2024-07-07 10:11 UTC, mialbu commented
I'll merge this. Please open a new PR if there's a test you'd like to add in the future.

2024-07-07 10:11 UTC, merged