add lock functionality
bane-labs/bridge-evm-contracts pull request #34
Opened 2023-12-26 09:52 UTC by cloud8little

close #33

2024-01-03 07:50 UTC, steven1227 approved these changes

2024-01-04 22:57 UTC, gsmachado commented
IMHO, this PR is fine.

2024-01-10 09:27 UTC, cloud8little commented
@mialbu  shall we merge?

2024-01-15 17:38 UTC, mialbu requested changes
Please take a look at [this document](https://github.com/bane-labs/bridge-docs/blob/bb5884260e65aa03fb4be350a37032778b780b6f/roles.md) and change the naming of admin and recoverer in the contract.

2024-01-15 17:38 UTC, mialbu commented on contracts/BridgeContract.sol
> +    function unLock() external onlyRecoverer {
```suggestion
    function unlock() external onlyGovernor {
```

2024-01-17 08:09 UTC, cloud8little commented
@mialbu  all resolved in https://github.com/bane-labs/bridge-evm-contracts/pull/34/commits/0671d84dfdbf3be7529a24ab8d22d6caee6838a8

2024-01-18 17:56 UTC, mialbu approved these changes

2024-01-18 17:57 UTC, merged