Fungible Token Integration
bane-labs/bridge-evm-contracts pull request #85
Opened 2024-05-02 18:34 UTC by mialbu

This PR is still WIP.

Closes #86 
Closes #84 
Closes #83 
Closes #55
Closes #87
Closes #88

- Added `nonReentrant` modifier to `deposit()`, `claim()`, `depositToken()` and `claimToken()`

2024-05-06 08:42 UTC, txhsl requested changes

2024-05-06 08:42 UTC, txhsl commented on contracts/interfaces/IERC20Capped.sol
> +interface IERC20Capped {
`ERC20Capped` is an existing template in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v5.0/contracts/token/ERC20/extensions/ERC20Capped.sol), I think they are different things, maybe rename this interface.

If this interface is meant to allow ERC-20 transfer, then just import https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v5.0/contracts/token/ERC20/IERC20.sol, instead of creating a new one.

2024-05-06 08:42 UTC, txhsl commented on contracts/library/BridgeLib.sol
> +        return uint256(_value / (10 ** 10));
Maybe we don't need this `uint256()` convert.

2024-05-06 08:42 UTC, txhsl commented on contracts/base/IGasBridge.sol
> +    function deposit(
`depositGAS`.

2024-05-06 08:42 UTC, txhsl commented on contracts/base/ITokenBridge.sol
> +    function depositToken(
If we are going to allow ERC20 here, then use `depositERC20` and `ERC20Bridge`.

2024-05-06 08:42 UTC, txhsl commented on contracts/base/IBridge.sol
> +    function lock() external;
Maybe move this `lock()` and `unlock()` to `IGasBridge.sol`.

2024-05-06 08:42 UTC, txhsl commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
Are we going to support `ERC20Uncapped`? I'm afraid not, and I don't think it will be compatible with method `depositToken()`.

For example, `ERC721` bridge is somehow different from `ERC20` Bridge, there will be a `tokenId` in transfer method, instead of the `value`. Please refer to https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v5.0/contracts/token/ERC721/IERC721.sol. We may need another bridge lib for this.

2024-05-06 08:42 UTC, txhsl commented on contracts/base/BridgeImpl.sol
> +    function claim(uint256 _nonce) external unlocked {
It is necessary to use `ReentrancyGuard` when there is a message calling to outside (e.g. `to.call{}()`), to prevent potential attack, for the safety of future maintenance. Please refer to https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v5.0/contracts/utils/ReentrancyGuard.sol.

2024-05-06 08:42 UTC, txhsl commented on contracts/base/BridgeImpl.sol
> +    function withdrawToken(uint256 _amount, address _to) external override {
The fee logic is missing here.

2024-05-06 08:42 UTC, txhsl commented on contracts/base/BridgeStorage.sol
> +    mapping(uint256 id => BridgeStorageTypes.TokenBridge) public tokens;
Maybe rename this `tokens` to `bridges` or something else.

2024-05-06 08:42 UTC, txhsl commented on contracts/base/BridgeStorage.sol
> +    constructor(address _management) {
The initialization of `TokenTypeConfig` is necessary.

2024-05-06 08:42 UTC, txhsl commented on contracts/library/BridgeStorageTypes.sol
> +        bool registered; // used for simple existence check
The storage of `registered` is a bit of redundant. It is not expensive, but maybe check something else.

2024-05-06 08:42 UTC, txhsl commented on contracts/base/BridgeStorage.sol
> +        assert(tokenIds[_tokenConfig.contractAddress] == 0);
The `id` and `address` are both unique identifiers. Why not just use the contract address as the key of the mapping, so that we don't have to bind it with its `_id` and make this check?

2024-05-06 08:42 UTC, txhsl commented on contracts/base/BridgeStorage.sol
> +    function _getTokenTypeConfig(
The setter for `TokenTypeConfig` seems missing.

2024-05-06 08:45 UTC, txhsl commented
Sorry, I know this PR is WIP, but I'm requested to have a review. :)

2024-05-06 11:58 UTC, mialbu commented on contracts/base/ITokenBridge.sol
> +    function depositToken(
You're right, I'll rename it. However, to give you some context: I've called it `depositToken` because with the current design around creating new hashes from token deposits, it will be very simple to include ERC721 tokens as well, as long as only the `tokenId` is needed and no metadata needs to be bridged. For example, an NFT mint or transfer also requires an `address` and a `uint256` parameter which suits the current design around creating a hash from that data.

👇🏼 

In order to restrict any signature replay attacks, I've added an identifier to the hash process for tokens. For GAS it's `sha256(concat(nonce, amount, to))` (i.e., `sha256(concat(uint256, uint256, address))`), and for tokens it's `sha256(concat(id, nonce, amount, to))` (i.e., `sha256(concat(uint256, uint256, uint256, address))`), where the `amount` could act as the `tokenId` for NFTs.

2024-05-06 11:59 UTC, mialbu commented on contracts/base/BridgeImpl.sol
> +    function claim(uint256 _nonce) external unlocked {
Done

2024-05-06 12:12 UTC, mialbu commented on contracts/base/BridgeStorage.sol
> +        assert(tokenIds[_tokenConfig.contractAddress] == 0);
> The `id` and `address` are both unique identifiers. Why not just use the contract address as the key of the mapping, so that we don't have to bind it with its `_id` and make this check?

They are, but only on either chain. The idea behind using a different unique identifier than the ERC20 address is that it can be used on N3 as well. Imo, we can use the ERC20 address as unique identifier, but then we'd need to store it's "counterpart" address of the N3 NEP-17 token here as well. I'd like that it's clear which hash chain belongs to which hash chain between Neo X and Neo N3, and this is achieved with an id in a nicer and cleaner way imho.

2024-05-06 12:37 UTC, mialbu commented on contracts/library/BridgeLib.sol
> +        return uint256(_value / (10 ** 10));
Addressed in [746f151](https://github.com/bane-labs/bridge-evm-contracts/pull/85/commits/746f15126ef3a85b4b16703eb49b41192591af64)

2024-05-06 12:38 UTC, mialbu commented on contracts/interfaces/IERC20Capped.sol
> +interface IERC20Capped {
Already did in the meantime 👍🏼

2024-05-06 12:44 UTC, mialbu commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
We can support `ERC20Uncapped`, just as well as `ERC721`. We just need to add some specific functionality instead of just calling `ERC20.transfer()`. The idea of the current `depositToken` function implementation is that based on the token type, different logic is executed on the destination contract, which might be a `ERC20Capped`, and `ERC20Uncapped` or an `ERC721`. There are some restrictions, but it's absolutely possible to do it. If a token owner doesn't want to give ownership to the bridge contract (i.e., to mint), we can introduce an intermediary contract, that will be called from the bridge contract, and that contract will be the token contract's owner.

2024-05-06 12:59 UTC, mialbu commented on contracts/library/BridgeStorageTypes.sol
> +        bool registered; // used for simple existence check
Fixed in [89a07ab](https://github.com/bane-labs/bridge-evm-contracts/pull/85/commits/89a07ab76462b0cb9b3aea1644ad0feb6b708ca1). Now using a check whether the token bridge's config's `contractAddress` is `address(0)`.

2024-05-06 13:16 UTC, mialbu commented on contracts/base/BridgeStorage.sol
> +    function _getTokenTypeConfig(
Added in [cb16577](https://github.com/bane-labs/bridge-evm-contracts/pull/85/commits/cb165778a17c41e0902202e10eeba09a364c7d30).

2024-05-06 14:24 UTC, mialbu commented on contracts/base/IBridge.sol
> +    function lock() external;
Depends whether we want to only lock the gas bridge separately. For tokens I think it's nice that they can be locked and unlocked individually. For Gas, I'm not so sure. Either way, I think we should have a complete lockdown functionality, and as it is now, `lock()` and `unlock()` could* act nicely as such. If we want to add functionality to lock the gas bridge individually, I think it's better to introduce a new value in storage with new functions, e.g., `un/lockGasBridge()`.

\*They currently don't, but it would suit the current storage design that we just add the locked/unlocked modifiers to the token functions as well.

2024-05-06 15:01 UTC, mialbu commented on contracts/base/BridgeImpl.sol
> +    function withdrawToken(uint256 _amount, address _to) external override {
Addressed in [f7171b7](https://github.com/bane-labs/bridge-evm-contracts/pull/85/commits/f7171b759d5f09769d1a3f55b0041f1732bf9b8e), please take a look.

2024-05-06 15:01 UTC, mialbu commented on contracts/base/BridgeStorage.sol
> +    mapping(uint256 id => BridgeStorageTypes.TokenBridge) public tokens;
Renamed to `tokenBridges` and `tokenBridgeIds`.

2024-05-06 15:05 UTC, mialbu commented on contracts/base/BridgeStorage.sol
> +    constructor(address _management) {
With the newly added function `setTokenTypeConfig()` it's not mandatory to have in the constructor. Also, once we use this contract for upgrading in T3, we need to use this setter function anyway. Once we go to mainnet, we should precompute its storage entries, or we don't and just need to be aware that we need to invoke the setter before registering any tokens of unset tokenTypeConfigs.

2024-05-06 15:06 UTC, mialbu commented on contracts/base/IGasBridge.sol
> +    function deposit(
I'll leave that open for now, but I tend to agree to a renaming here, maybe `depositGas` works as well.

2024-05-06 22:37 UTC, mialbu commented on contracts/base/IGasBridge.sol
> +    function deposit(
I've renamed gas-related exported functions in [51a969d](https://github.com/bane-labs/bridge-evm-contracts/pull/85/commits/51a969d17b6831246f2ac280f75c81fb0ea6c860), i.e., `depositGas()`, `claimGas()` and `withdrawGas()`. If you agree with the change, please mark this convo as resolved.

2024-05-07 02:14 UTC, txhsl commented on contracts/base/BridgeStorage.sol
> +        assert(tokenIds[_tokenConfig.contractAddress] == 0);
Fine.

2024-05-07 02:16 UTC, txhsl commented on contracts/base/BridgeStorage.sol
> +    constructor(address _management) {
> be aware that we need to invoke the setter before registering any tokens of unset tokenTypeConfigs.

Yes, this is important.

2024-05-07 02:39 UTC, txhsl commented on contracts/base/IBridge.sol
> +    function lock() external;
AFAIK, the `unlocked` modifier is only affecting `depositGas`, `claimGas` and `withdrawGas`, so it seems like a gas-bridge-only lock. Just put it at the correct place when we finalize the contract.

2024-05-07 02:42 UTC, txhsl commented on contracts/base/BridgeImpl.sol
> +    function withdrawToken(uint256 _amount, address _to) external override {
Should we charge GAS or the bridged token?

2024-05-07 02:45 UTC, txhsl commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
🤔Is there any case that we may bridge `ERC20Uncapped` on N3 or Neo X?

2024-05-07 03:08 UTC, txhsl commented on contracts/base/ITokenBridge.sol
> +    function depositToken(
Well, but take care because the `uint256` in `Claimable` data have different meanings.

2024-05-07 08:54 UTC, mialbu commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
> Is there any case that we may bridge `ERC20Uncapped` on N3 or Neo X?

Depends on demand ofc, but e.g., FLM has dynamic total supply afaik.

2024-05-07 08:56 UTC, mialbu commented on contracts/base/BridgeImpl.sol
> +    function withdrawToken(uint256 _amount, address _to) external override {
> Should we charge GAS or the bridged token?

Good question. Although, would we really want a token? @steven1227

2024-05-07 09:28 UTC, txhsl commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
Dynamic total supply is allowed by both ERC20 and NEP17.

2024-05-07 09:30 UTC, txhsl commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
Well, if we pack ERC20 and ERC721 in the same data structure, then we can leave this third type TBD.

2024-05-07 09:50 UTC, mialbu commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
Sure, the idea with the approach of having ERC20Capped and ERC20Uncapped is that on the destination chain when distributing we can differentiate between using `transfer()` and `mint()`.

It depends how we want anyone that requests to be registered should be included in the bridge. What should they provide once we accept a token to be supported by the bridge?

If it's a capped token, they can allocate the total supply on the destination chain to the bridge. Then we can just use `transfer` on the new ERC20 they deploy.

If it's an uncapped token, they might not like to put a hardcap allocation on the destination chain to the bridge, but rather ask if we can somehow mint. For this we either:
- need to support calling a `mint()` function that is `accessManaged`.
- they need to write some logic into their `transfer` function, such that if the `msg.sender` is the bridge, they mint instead of transfer.

Or we just create a well-defined interface that the bridge supports, and require anyone that wants to get registered to deploy a contract that adheres to that interface (and then they can add their logic in there - whether it'll be a mint/transfer/...).

2024-05-07 10:36 UTC, txhsl commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
> If it's a capped token, they can allocate the total supply on the destination chain to the bridge.

Well, I see the problem.

2024-05-07 14:56 UTC, gsmachado commented on contracts/base/BridgeImpl.sol
> +    function withdrawToken(uint256 _amount, address _to) external override {
In my opinion, we should charge $GAS.

2024-05-07 14:59 UTC, gsmachado commented on contracts/library/BridgeStorageTypes.sol
> +    enum TokenType {
> Well, I see the problem.

Usually, there are more problems than we imagine. 🤷‍♂️

2024-05-07 15:00 UTC, gsmachado commented on contracts/base/ITokenBridge.sol
> +    function depositToken(
@mialbu can we resolve this comment?

2024-05-07 15:14 UTC, mialbu commented on contracts/base/ITokenBridge.sol
> +    function depositToken(
Yes, I'm well aware of the different meanings. I'll keep the current naming. Once introducing support for NFTs is on the table, we should rename `amount`, e.g., to `value`. Until then, the current state of it is fine.

2024-05-16 07:08 UTC, txhsl requested changes

2024-05-16 07:08 UTC, txhsl commented on contracts/library/TokenBridgeLib.sol
> +        return neoXToken.transfer(_to, _amount);
Can merge to one line.

2024-05-16 07:08 UTC, txhsl commented on contracts/bridge/BridgeImpl.sol
> +    ) external override onlyTokenBridgeUnpaused(_neoXToken) onlyGovernor {
I see the gas bridge pause is `onlySecurityGuard`, but here the token bridge is `onlyGovernor`. What is the difference?

2024-05-16 07:08 UTC, txhsl commented on contracts/bridge/BridgeImpl.sol
> +        onlyTokenBridgeUnpaused(msg.sender)
Using `msg.sender` seems not correct.

2024-05-16 07:08 UTC, txhsl commented on contracts/library/StorageTypes.sol
> +        address neoN3Token;
Is this a token address on N3? If it is, then is it compatible to be stored in Solidity `address`?

2024-05-16 09:35 UTC, mialbu commented on contracts/library/StorageTypes.sol
> +        address neoN3Token;
It is. As far as I know, there's no checksum validation for address parameters. Thus, any value that is hexadecimal and 20 bytes long (which applies to any Neo N3 scripthash) is compatible.

Only if you provide a constant or initial value in solidity development, an address needs to be checksummed. Meaning the solidity compiler checks any address at compile time, but in the deployed script there's no such check.

2024-05-16 09:36 UTC, mialbu commented on contracts/bridge/BridgeImpl.sol
> +    ) external override onlyTokenBridgeUnpaused(_neoXToken) onlyGovernor {
No difference. It should be `onlySecurityGuard`. I'll change it.

2024-05-16 10:56 UTC, mialbu commented on contracts/bridge/BridgeImpl.sol
> +    ) external override onlyTokenBridgeUnpaused(_neoXToken) onlyGovernor {
Done in a13ec41c8080ff9f8c5383adad59ecf064326e8f.

2024-05-16 10:58 UTC, mialbu commented on contracts/library/TokenBridgeLib.sol
> +        return neoXToken.transfer(_to, _amount);
Done in 5a0a52c4b6b1afd72190fae053574b7ad013adcd.

2024-05-16 11:36 UTC, mialbu commented on contracts/bridge/BridgeImpl.sol
> +        onlyTokenBridgeUnpaused(msg.sender)
You're correct, I've changed it to `_neoXToken` in 9a206c7762c9c1c40aaaa73e32f74b932b2ae8d0.

2024-05-16 11:37 UTC, mialbu commented
@txhsl
Fyi, I've also added `_disableInitializers()` in the constructor of the `BridgeStorage.sol` contract in 00ece04b3bf2459dc77a4406f7cd420a7f9372d8.

2024-05-17 09:22 UTC, txhsl approved these changes

2024-05-17 09:23 UTC, merged